# .github/workflows/executar-testes.yml
# VERSÃO FINAL COM VARIÁVEIS EM MINÚSCULO PARA O ROBOT

name: Validar Testes Automatizados (Robot Framework)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  executar-testes:
    name: Executar Suíte de Testes Robot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes Robot
        run: |
          robot --variable URL:"${{ secrets.TARGET_APP_URL }}" \
                --variable admin_email:"${{ secrets.ADMIN_EMAIL }}" \
                --variable admin_password:"${{ secrets.ADMIN_PASSWORD }}" \
                --variable user_email:"${{ secrets.USER_EMAIL }}" \
                --variable user_password:"${{ secrets.USER_PASSWORD }}" \
                -d logs tests/

      - name: Upload dos resultados
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-robot
          path: logs/